version: '3.3'


services:
  app:
    build: .
    ports:
      - "8085-8088:8088"
    restart: unless-stopped  
    networks:
      - metrics-monitor 


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./env/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
    restart: unless-stopped    
    networks:
      - metrics-monitor
    depends_on:
      - cadvisor
      - node-exporter
      
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
    - '9100:9100'
    restart: unless-stopped  
    networks:
      - metrics-monitor  
      
      
      
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./env/grafana_conf/provisioning:/etc/grafana/provisioning
      - ./env/grafana_conf/custom_dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    restart: unless-stopped    
    networks:
      - metrics-monitor  
    env_file:
      - ./env/grafana.env
      
      
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    restart: unless-stopped  
    networks:
      - metrics-monitor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - app

    
networks:
  metrics-monitor:
    driver: bridge   


